# -*- coding: utf-8 -*-
"""prompt_based_sql_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VDT9Xuq0NcMbtruRjJ0SMfeCkGb7Odhd
"""

import sqlite3


conn = sqlite3.connect(":memory:")
cursor = conn.cursor()


cursor.execute("""
CREATE TABLE students (
    id INTEGER PRIMARY KEY,
    name TEXT,
    marks INTEGER
)
""")


students_data = [
    (1, "Alice", 85),
    (2, "Bob", 72),
    (3, "Charlie", 90),
    (4, "David", 65)

]

cursor.executemany("INSERT INTO students VALUES (?, ?, ?)", students_data)
conn.commit()


def handle_prompt(prompt):
    prompt = prompt.lower()

    if "all students" in prompt:
        query = "SELECT * FROM students"

    elif "above 80" in prompt:
        query = "SELECT * FROM students WHERE marks > 80"

    elif "below 70" in prompt:
        query = "SELECT * FROM students WHERE marks < 70"

    else:
        return "Sorry, query not recognized."

    cursor.execute(query)
    return cursor.fetchall()


user_prompt = input("Enter your SQL prompt: ")
result = handle_prompt(user_prompt)

print("\nQuery Result:\n")
print(result)